# Generated by Django 2.2 on 2019-10-07 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_homepage', '0003_image_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('groupsize', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(max_length=200)),
                ('appointment', models.DateTimeField(auto_now=True)),
                ('miscellaneous', models.TextField(blank=True)),
            ],
        ),
    ]
