# Generated by Django 2.2 on 2019-10-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_homepage', '0004_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='phone',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='appointment',
            field=models.DateTimeField(),
        ),
    ]
